=== gadgetron/gadgetron/apps/gadgetron/schema/gadgetron.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://gadgetron.sf.net/gadgetron" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gadgetron.sf.net/gadgetron">

    <!--
    Gadgetron configuration xml includes two sections: port and globalGadgetParameters
    The 'port' is where gadgetron is listening to. The 'globalGadgetParameters' section 
    lists the parameters which will be pre-set for all gadgets
    e.g. if 'workingDirectory' in the globalGadgetParameters is set, the dependency measurements
    will be stored and read from this directory. If it is not set, the default
    directory will be used ('/tmp/gadgetron' in linux and 'c:/temp/gadgetron' in windows).
    -->
    <xs:complexType name="Readers">
        <xs:sequence>
            <xs:element name="reader" type="Reader"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Writers">
        <xs:sequence>
            <xs:element name="reader" type="Reader"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="configuration">
        <xs:complexType>
            <xs:all>
            <xs:element name="version" type="xs:string"/>
                <xs:element name="readers" type="Readers"/>
                <xs:element name="writers" type="Writers"/>
                <xs:element name="stream" type="Stream" />

            </xs:all>
        </xs:complexType>

    </xs:element>



  <xs:element name="gadgetronStreamConfiguration">
    <xs:complexType>
      <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reader">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element name="slot" type="xs:unsignedShort"/>
                              <xs:element name="dll" type="xs:string"/>
                              <xs:element name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="writer">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1" name="slot" type="xs:unsignedShort"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="gadget">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1"  name="name" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                                  <xs:complexType>
                                      <xs:sequence>
                                          <xs:element maxOccurs="1" minOccurs="1" name="name" type="xs:string"/>
                                          <xs:element maxOccurs="1" minOccurs="1" name="value" type="xs:string"/>
                                      </xs:sequence>        
                                  </xs:complexType>
                              </xs:element>
                             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gadgetron/gadgetron/gadgets/debugging/config/pseudoreplica_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <reader>
        <slot>1008</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
    <reader>
        <slot>1026</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdWaveformMessageReader</classname>
    </reader>

  <writer>
    <slot>1022</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriter</classname>
  </writer>

  <gadget>
    <name>NoiseAdjust</name>
    <dll>gadgetron_mricore</dll>
    <classname>NoiseAdjustGadget</classname>
  </gadget>
  
  <gadget>
    <name>PCA</name>
    <dll>gadgetron_mricore</dll>
    <classname>PCACoilGadget</classname>
  </gadget>
  
  <gadget>
    <name>CoilReduction</name>
    <dll>gadgetron_mricore</dll>
    <classname>CoilReductionGadget</classname>
    <property><name>coils_out</name><value>16</value></property>
  </gadget>
  
  <gadget>
    <name>RemoveROOversampling</name>
    <dll>gadgetron_mricore</dll>
    <classname>RemoveROOversamplingGadget</classname>
  </gadget>

    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property>
            <name>trigger_dimension</name>
            <value>none</value>
        </property>
        <property>
          <name>sorting_dimension</name>
          <value>none</value>
        </property>
    </gadget>

    <gadget>
        <name>Buff</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property>
            <name>N_dimension</name>
            <value>repetition</value>
        </property>
        <property>
          <name>S_dimension</name>
          <value></value>
        </property>
        <property>
          <name>split_slices</name>
          <value>false</value>
        </property>
    </gadget>

	<gadget>
		<name>PseudoReplicatorGadget</name>
		<dll>gadgetron_debugging</dll>
		<classname>PseudoReplicatorGadget</classname>
		<property>
			<name>repetitions</name>
			<value>100</value>
		</property>
	</gadget>

  <gadget>
		<name>StandardDeviationGadget</name>
		<dll>gadgetron_debugging</dll>
		<classname>StandardDeviationGadget</classname>
    <property>
			<name>errorThreshold</name>
			<value>0.000001</value>
		</property>
	</gadget>

  <gadget>
    <name>ImageArraySplit</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageArraySplitGadget</classname>
  </gadget>
    
  <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
  </gadget>
  
  <gadget>
    <name>Extract</name>
    <dll>gadgetron_mricore</dll>
    <classname>ExtractGadget</classname>
  </gadget>

  <gadget>
    <name>ImageFinish</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageFinishGadget</classname>
  </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/hyper/CMRT.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
    <gadget>
      <name>CMRT</name>
      <dll>gadgetron_hyper</dll>
      <classname>CMRTGadget</classname>
      <property><name>projections_per_recon</name><value>128</value></property>
      <property>
      	<name>golden_ratio</name>
      	<value>true</value></property></gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>  

    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/config/NoiseSummary.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <writer>
        <slot>1019</slot>
        <dll>gadgetron_mricore</dll>
        <classname>DependencyQueryWriter</classname>
    </writer>

    <gadget>
        <name>NoiseSummary</name>
        <dll>gadgetron_mricore</dll>
        <classname>NoiseSummaryGadget</classname>

        <property>
            <name>noise_file</name>
            <value>NAMEOFNOISEFILE</value>
        </property>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/config/default_short.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <reader>
        <slot>1008</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
    <reader>
        <slot>1026</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdWaveformMessageReader</classname>
    </reader>
 
    <writer>
      <slot>1022</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriter</classname>
    </writer>

    <gadget>
        <name>RemoveROOversampling</name>
        <dll>gadgetron_mricore</dll>
        <classname>RemoveROOversamplingGadget</classname>
    </gadget>

    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property>
            <name>trigger_dimension</name>
            <value>repetition</value>
        </property>
        <property>
          <name>sorting_dimension</name>
          <value>slice</value>
        </property>
    </gadget>

    <gadget>
        <name>Buff</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property>
            <name>N_dimension</name>
            <value></value>
        </property>
        <property>
          <name>S_dimension</name>
          <value></value>
        </property>
        <property>
          <name>split_slices</name>
          <value>true</value>
        </property>
    </gadget>

     <gadget>
      <name>SimpleRecon</name>
      <dll>gadgetron_mricore</dll>
      <classname>SimpleReconGadget</classname>
     </gadget>

     <gadget>
      <name>ImageArraySplit</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageArraySplitGadget</classname>
     </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_mricore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>

    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>

     <gadget>
      <name>ImageFinish</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_noncartesian/config/Generic_Spiral.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- reader -->
    <reader><slot>1008</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdAcquisitionMessageReader</classname></reader>
    <reader><slot>1026</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdWaveformMessageReader</classname></reader>

    <!-- writer -->
    <writer><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageWriter</classname></writer>

    <!-- Noise prewhitening -->
    <gadget><name>NoiseAdjust</name><dll>gadgetron_mricore</dll><classname>NoiseAdjustGadget</classname></gadget>

  <gadget>
    <name>PCA</name>
    <dll>gadgetron_mricore</dll>
    <classname>PCACoilGadget</classname>
  </gadget>

  <gadget>
    <name>CoilReduction</name>
    <dll>gadgetron_mricore</dll>
    <classname>CoilReductionGadget</classname>
    <property><name>coils_out</name><value>16</value></property>
  </gadget>

    <!-- Calculate spiral trajectory and attach -->
    <gadget>
        <name>SpiralToGeneric</name>
        <dll>gadgetron_spiral</dll>
        <classname>SpiralToGenericGadget</classname>
    </gadget>
    
    <!-- Data accumulation and trigger gadget -->
    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property><name>trigger_dimension</name><value>repetition</value></property>
        <property><name>sorting_dimension</name><value></value></property>
    </gadget>

    <gadget>
        <name>BucketToBuffer</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property><name>N_dimension</name><value>phase</value></property>
        <property><name>S_dimension</name><value>set</value></property>
        <property><name>split_slices</name><value>false</value></property>
        <property><name>ignore_segment</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>
    </gadget>

    <gadget>
        <name>GriddingRecon</name>
        <dll>gadgetron_mri_noncartesian</dll>
        <classname>GriddingReconGadget</classname>
        <property><name>verbose</name><value>true</value></property>	
        <property><name>perform_timing</name><value>true</value></property>

	<!-- Ignore gridding weights, iterate instead -->
	<!--
	    <property><name>iterate</name><value>true</value></property>
	    <property><name>iteration_max</name><value>10</value></property>
	    <property><name>iteration_tol</name><value>1e-3</value></property>
	-->

	<!--
	    To measure SNR on frame 20 using pseudo replicas, enable lines below 
	    <property><name>replicas</name><value>256</value></property>
	    <property><name>snr_frame</name><value>20</value></property>
	-->
	
    </gadget>

    
    <!-- Image Array Scaling -->
    <gadget>
        <name>Scaling</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconImageArrayScalingGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>perform_timing</name><value>false</value></property>
        <property><name>verbose</name><value>false</value></property>

        <property><name>min_intensity_value</name><value>64</value></property>
        <property><name>max_intensity_value</name><value>4095</value></property>
        <property><name>scalingFactor</name><value>10.0</value></property>
        <property><name>use_constant_scalingFactor</name><value>true</value></property>
        <property><name>auto_scaling_only_once</name><value>true</value></property>
        <property><name>scalingFactor_dedicated</name><value>100.0</value></property>
    </gadget>

    <!-- ImageArray to images -->
    <gadget>
        <name>ImageArraySplit</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageArraySplitGadget</classname>
    </gadget>

    <!-- after recon processing -->
    <gadget>
        <name>ComplexToFloatAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>ComplexToFloatGadget</classname>
    </gadget>

    <!--<gadget>-->
        <!--<name>FloatToShortAttrib</name>-->
        <!--<dll>gadgetron_mricore</dll>-->
        <!--<classname>FloatToUShortGadget</classname>-->

        <!--<property><name>max_intensity</name><value>32767</value></property>-->
        <!--<property><name>min_intensity</name><value>0</value></property>-->
        <!--<property><name>intensity_offset</name><value>0</value></property>-->
    <!--</gadget>-->
    <!---->
    <gadget>
        <name>ImageFinish</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/Generic_Cartesian_Grappa_RealTimeCine.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!--
        Gadgetron generic recon chain for 2D and 3D cartesian sampling

        RealTimeCine imaging
        Triggered by slice
        Recon N is phase and S is set

        Author: Hui Xue
        Magnetic Resonance Technology Program, National Heart, Lung and Blood Institute, National Institutes of Health
        10 Center Drive, Bethesda, MD 20814, USA
        Email: hui.xue@nih.gov
    -->

    <!-- reader -->
    <reader><slot>1008</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdAcquisitionMessageReader</classname></reader>

    <!-- writer -->
    <writer><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageWriter</classname></writer>

    <!-- Noise prewhitening -->
    <gadget><name>NoiseAdjust</name><dll>gadgetron_mricore</dll><classname>NoiseAdjustGadget</classname></gadget>

    <!-- RO asymmetric echo handling -->
    <gadget><name>AsymmetricEcho</name><dll>gadgetron_mricore</dll><classname>AsymmetricEchoAdjustROGadget</classname></gadget>

    <!-- RO oversampling removal -->
    <gadget><name>RemoveROOversampling</name><dll>gadgetron_mricore</dll><classname>RemoveROOversamplingGadget</classname></gadget>

    <!-- Data accumulation and trigger gadget -->
    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property><name>trigger_dimension</name><value>slice</value></property>
        <property><name>sorting_dimension</name><value>slice</value></property>
    </gadget>

    <gadget>
        <name>Buff</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property><name>N_dimension</name><value>phase</value></property>
        <property><name>S_dimension</name><value>set</value></property>
        <property><name>split_slices</name><value>true</value></property>
        <property><name>ignore_segment</name><value>true</value></property>
    </gadget>

    <!-- Prep ref -->
    <gadget>
        <name>PrepRef</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericCartesianReconReferencePrepGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value>DebugFolder</value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>

        <!-- averaging across repetition -->
        <property><name>average_all_ref_N</name><value>true</value></property>

        <!-- every set has its own kernels -->
        <property><name>average_all_ref_S</name><value>false</value></property>
    </gadget>

    <!-- Recon -->
    <gadget>
        <name>Recon</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericCartesianGrappaReconGadget</classname>

        <!-- image series -->
        <property><name>image_series</name><value>0</value></property>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value>DebugFolder</value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>

        <!-- whether to send out gfactor -->
        <property><name>send_out_gfactor</name><value>true</value></property>
    </gadget>

    <!-- Partial fourier handling -->
    <gadget>
        <name>PartialFourierHandling</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconPartialFourierHandlingPOCSGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value>DebugFolder</value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>

        <!-- if incoming images have this meta field, it will not be processed -->
        <property><name>skip_processing_meta_field</name><value>Skip_processing_after_recon</value></property>

        <!-- Parfial fourier POCS parameters -->
        <property><name>partial_fourier_POCS_iters</name><value>6</value></property>
        <property><name>partial_fourier_POCS_thres</name><value>0.01</value></property>
        <property><name>partial_fourier_POCS_transitBand</name><value>24</value></property>
        <property><name>partial_fourier_POCS_transitBand_E2</name><value>16</value></property>
    </gadget>

    <!-- ImageArray to images -->
    <gadget>
        <name>ImageArraySplit</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageArraySplitGadget</classname>
    </gadget>

    <!-- after recon processing -->
    <gadget>
        <name>ComplexToFloatAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>ComplexToFloatGadget</classname>
    </gadget>

    <gadget>
        <name>ImageFinish</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/config/default_measurement_dependencies.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
                  xmlns="http://gadgetron.sf.net/gadgetron"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- SNR unit noise adjust gadget
         If the scan has asymmetric readout, the center of echo will shifted to the index 0
         Zeros will be filled into the readout data
    -->
    <gadget>
        <name>NoiseAdjust</name>
        <dll>pingvin_mricore</dll>
        <classname>NoiseAdjustGadget</classname>

        <!-- Whether to pass the nonconformant data without applying the prewhitening -->
        <property>
            <name>pass_nonconformant_data</name>
            <value>true</value>
        </property>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/unified.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
  
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
  
    <gadget>
        <name>Accc</name>
        <dll>gadgetron_mricore</dll>
	<classname>AcquisitionAccumulateTriggerGadget</classname>
        <property>
            <name>trigger_dimension</name>
            <value>repetition</value>
        </property>
        <property>
          <name>sorting_dimension</name>
          <value>slice</value>
        </property>
    </gadget>

</gadgetronStreamConfiguration>
