=== gadgetron/gadgetron/apps/gadgetron/schema/gadgetron.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://gadgetron.sf.net/gadgetron" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gadgetron.sf.net/gadgetron">

    <!--
    Gadgetron configuration xml includes two sections: port and globalGadgetParameters
    The 'port' is where gadgetron is listening to. The 'globalGadgetParameters' section 
    lists the parameters which will be pre-set for all gadgets
    e.g. if 'workingDirectory' in the globalGadgetParameters is set, the dependency measurements
    will be stored and read from this directory. If it is not set, the default
    directory will be used ('/tmp/gadgetron' in linux and 'c:/temp/gadgetron' in windows).
    -->
    <xs:complexType name="Readers">
        <xs:sequence>
            <xs:element name="reader" type="Reader"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Writers">
        <xs:sequence>
            <xs:element name="reader" type="Reader"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="configuration">
        <xs:complexType>
            <xs:all>
            <xs:element name="version" type="xs:string"/>
                <xs:element name="readers" type="Readers"/>
                <xs:element name="writers" type="Writers"/>
                <xs:element name="stream" type="Stream" />

            </xs:all>
        </xs:complexType>

    </xs:element>



  <xs:element name="gadgetronStreamConfiguration">
    <xs:complexType>
      <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reader">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element name="slot" type="xs:unsignedShort"/>
                              <xs:element name="dll" type="xs:string"/>
                              <xs:element name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="writer">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1" name="slot" type="xs:unsignedShort"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="gadget">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1"  name="name" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                                  <xs:complexType>
                                      <xs:sequence>
                                          <xs:element maxOccurs="1" minOccurs="1" name="name" type="xs:string"/>
                                          <xs:element maxOccurs="1" minOccurs="1" name="value" type="xs:string"/>
                                      </xs:sequence>        
                                  </xs:complexType>
                              </xs:element>
                             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gadgetron/gadgetron/gadgets/bart/BART_Recon.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!--
        Gadgetron generic recon chain for 2D and 3D cartesian sampling

        RealTimeCine imaging
        Triggered by slice
        Recon N is phase and S is set

        Author: Hui Xue
        Magnetic Resonance Technology Program, National Heart, Lung and Blood Institute, National Institutes of Health
        10 Center Drive, Bethesda, MD 20814, USA
        Email: hui.xue@nih.gov
    -->

    <!-- reader -->
    <reader><slot>1008</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdAcquisitionMessageReader</classname></reader>

    <!-- writer -->
    <writer><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageWriter</classname></writer>

    <!-- Noise prewhitening -->
    <gadget><name>NoiseAdjust</name><dll>gadgetron_mricore</dll><classname>NoiseAdjustGadget</classname></gadget>

    <!-- RO asymmetric echo handling -->
    <gadget><name>AsymmetricEcho</name><dll>gadgetron_mricore</dll><classname>AsymmetricEchoAdjustROGadget</classname></gadget>

    <!-- RO oversampling removal -->
    <gadget><name>RemoveROOversampling</name><dll>gadgetron_mricore</dll><classname>RemoveROOversamplingGadget</classname></gadget>

    <!-- Data accumulation and trigger gadget -->
    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property><name>trigger_dimension</name><value>slice</value></property>
        <property><name>sorting_dimension</name><value></value></property>
    </gadget>

    <gadget>
        <name>BucketToBuffer</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property><name>N_dimension</name><value>phase</value></property>
        <property><name>S_dimension</name><value>set</value></property>
        <property><name>split_slices</name><value>true</value></property>
        <property><name>ignore_segment</name><value>true</value></property>
    </gadget>

	<!-- Prep ref -->
    <gadget>
        <name>PrepRef</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconCartesianReferencePrepGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value></value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>

        <!-- averaging across repetition -->
        <property><name>average_all_ref_N</name><value>true</value></property>
        <!-- every set has its own kernels -->
        <property><name>average_all_ref_S</name><value>false</value></property>
        <!-- whether always to prepare ref if no acceleration is used -->
        <property><name>prepare_ref_always</name><value>true</value></property>
    </gadget>
	
	<!-- This is where we insert our new Gadget -->
	<gadget>
	  <name>bartgadget</name>
	  <dll>gadgetron_bart</dll>
	  <classname>BartGadget</classname>
	  <BartCommandsFile>Sample_Grappa_Recon.txt</BartCommandsFile>
	  <property><name>BartCommandScript_path</name><value>share/gadgetron/bart</value></property>
      <property><name>BartCommandScript_name</name><value>Sample_Grappa_Recon.txt</value></property>
	</gadget>
		
    <!-- ImageArray to images -->
    <gadget>
        <name>ImageArraySplit</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageArraySplitGadget</classname>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_mricore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>
    
    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
	
    <gadget>
        <name>ImageFinish</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/spiral/config/spiral_interactive.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <reader>
    <slot>1008</slot>
    <dll>gadgetron_mricore</dll>
    <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
  </reader>
    <reader>
        <slot>1026</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdWaveformMessageReader</classname>
    </reader>
  <writer>
    <slot>1022</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriter</classname>
  </writer>

  <gadget>
    <name>NoiseAdjust</name>
    <dll>gadgetron_mricore</dll>
    <classname>NoiseAdjustGadget</classname>
  </gadget>
  
  <gadget>
    <name>PCA</name>
    <dll>gadgetron_mricore</dll>
    <classname>PCACoilGadget</classname>
  </gadget>
  
  <gadget>
    <name>CoilReduction</name>
    <dll>gadgetron_mricore</dll>
    <classname>CoilReductionGadget</classname>
    <property><name>coils_out</name><value>8</value></property>
  </gadget>

  <gadget>
    <name>gpuSpiralSensePrepGadget</name>
    <dll>gadgetron_spiral</dll>
    <classname>gpuSpiralSensePrepGadget</classname>
    <property><name>deviceno</name><value>0</value></property>
    <property><name>buffer_convolution_kernel_width</name><value>4.5</value></property>
    <property><name>buffer_convolution_oversampling_factor</name><value>1.25</value></property>
  </gadget>
  
  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>0</value></property>
    <property><name>number_of_iterations</name>    <value>5</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>4.5</value></property>
    <property><name>kappa</name>                   <value>0.3</value></property>
  </gadget>

  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>1</value></property>
    <property><name>number_of_iterations</name>    <value>5</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>4.5</value></property>
    <property><name>kappa</name>                   <value>0.3</value></property>
  </gadget>

  <gadget>
    <name>Extract</name>
    <dll>gadgetron_mricore</dll>
    <classname>ExtractGadget</classname>
  </gadget>
  
  <!--
      <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
      </gadget>
  -->    
  
  <gadget>
    <name>AutoScaleGadget</name>
    <dll>gadgetron_mricore</dll>
    <classname>AutoScaleGadget</classname>
  </gadget> 

  <gadget>
    <name>FloatToShort</name>
    <dll>gadgetron_mricore</dll>
    <classname>FloatToUShortGadget</classname>
  </gadget>

  <gadget>
    <name>ImageFinish</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageFinishGadget</classname>
  </gadget>    

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/config/gtquery.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <writer>
        <slot>1019</slot>
        <dll>gadgetron_mricore</dll>
        <classname>DependencyQueryWriter</classname>
    </writer>

    <gadget>
        <name>DependencyQuery</name>
        <dll>gadgetron_mricore</dll>
        <classname>DependencyQueryGadget</classname>

        <!-- If set to true, check the file creation time and delete old stored files -->
        <property>
            <name>clean_storage_while_query</name>
            <value>true</value>
        </property>

        <!-- In the unit of hours, the maximal time duration allowed for a file stored
             If clean_storage_while_query == true, this time limit will be used to 
             determine which files to be deleted
         -->
        <property>
            <name>time_limit_in_storage</name>
            <value>24.0</value>
        </property>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/cmr/config/LandmarkDetection/CMR_Image_Chain_RTCine_LAX_AI.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!--
        Gadgetron generic image analysis chain for CMR

        Cine Landmark Detection
        Triggered by slice
        Working on phases

        Author: Hui Xue
        National Heart, Lung and Blood Institute, National Institutes of Health
        10 Center Drive, Bethesda, MD 20814, USA
        Email: hui.xue@nih.gov
    -->

    <!-- reader -->
    <reader><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageReader</classname></reader>

    <!-- writer -->
    <writer><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageWriter</classname></writer>

    <!-- Convert image to image array -->
    <gadget>
        <name>ImageToArray</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconImageToImageArrayGadget</classname>
        <property><name>verbose</name><value>false</value></property>
    </gadget>

    <!-- Image recon accummulator -->
    <gadget>
        <name>ImageAcc</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconAccumulateImage2DTriggerGadget</classname>

        <!-- triggered dimensions -->
        <property><name>TriggerChannel</name><value>false</value></property>
        <property><name>TriggerSlice</name><value>true</value></property>
        <property><name>TriggerContrast</name><value>false</value></property>
        <property><name>TriggerPhase</name><value>true</value></property>
        <property><name>TriggerRepetition</name><value>false</value></property>
        <property><name>TriggerSet</name><value>false</value></property>
        <property><name>TriggerAverage</name><value>false</value></property>

        <!-- work flow -->
        <property><name>PassImageImmediately</name><value>false</value></property>

        <!-- debug and info mode -->
        <property><name>verbose</name><value>true</value></property>
    </gadget>

    <!-- LAX landmark detection -->
    <gadget>
        <name>LAXAI</name>
        <dll>gadgetron_cmr</dll>
        <classname>CmrRealTimeLAXCineAIAnalysisGadget</classname>

        <property><name>perform_AI</name><value>true</value></property>

        <!-- parameters for debug and timing -->
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>
        <property><name>debug_folder</name><value></value></property>
    </gadget>

    <!-- ImageArray to images -->
    <gadget>
        <name>ImageArraySplit</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageArraySplitGadget</classname>
    </gadget>

    <!-- after recon processing -->
    <gadget>
        <name>ComplexToFloatAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>ComplexToFloatGadget</classname>
    </gadget>

    <gadget>
        <name>FloatToShortAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>FloatToUShortGadget</classname>
    </gadget>

    <gadget>
        <name>ImageFinish</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/grappa/config/grappa.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
     <writer>
      <slot>1022</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriter</classname>
    </writer>

    <gadget>
      <name>NoiseAdjust</name>
      <dll>gadgetron_mricore</dll>
      <classname>NoiseAdjustGadget</classname>
    </gadget>

   <gadget>
      <name>PCA</name>
      <dll>gadgetron_mricore</dll>
      <classname>PCACoilGadget</classname>
    </gadget>

    <gadget>
      <name>CoilReduction</name>
      <dll>gadgetron_mricore</dll>
      <classname>CoilReductionGadget</classname>
      <property><name>coils_out</name><value>16</value></property>
    </gadget>
    
    <gadget>
      <name>RemoveROOversampling</name>
      <dll>gadgetron_mricore</dll>
      <classname>RemoveROOversamplingGadget</classname>
    </gadget>

    <gadget>
      <name>Grappa</name>
      <dll>gadgetron_grappa</dll>
      <classname>GrappaGadget</classname>
      <property><name>target_coils</name><value>8</value></property>
    </gadget>

    <gadget>
      <name>GrappaUnmixing</name>
      <dll>gadgetron_grappa</dll>
      <classname>GrappaUnmixingGadget</classname>
    </gadget>

     <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_mricore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>
    
    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>

    <gadget>
      <name>ImageFinish</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/matlab/matlabnoncartesian.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <reader>
    <slot>1008</slot>
    <dll>gadgetron_mricore</dll>
    <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
  </reader>

  <writer>
    <slot>1022</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriter</classname>
  </writer>

    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property>
            <name>trigger_dimension</name>
            <value>repetition</value>
        </property>
    </gadget>

    <gadget>
        <name>Buff</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property>
            <name>N_dimension</name>
            <value></value>
        </property>
        <property>
          <name>S_dimension</name>
          <value></value>
        </property>
        <property>
          <name>split_slice</name>
          <value>true</value>
        </property>
    </gadget>


  <gadget>
    <name>MatlabBuffer</name>
    <dll>gadgetron_matlab</dll>
    <classname>MatlabBufferGadget</classname>
    <property><name>debug_mode</name><value>1</value></property>
    <property><name>matlab_path</name><value></value></property>
    <property><name>matlab_classname</name><value>trajectoryScale</value></property>
    <property><name>matlab_port</name><value>3000</value></property>
  </gadget>
  <gadget>
    <name>Combine</name>
    <dll>gadgetron_mricore</dll>
    <classname>CombineGadget</classname>
  </gadget>
  <gadget>
    <name>Extract</name>
    <dll>gadgetron_mricore</dll>
    <classname>ExtractGadget</classname>
  </gadget>
  <gadget>
    <name>ImageFinish</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageFinishGadget</classname>
  </gadget>
</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/examples/config/stream_float_to_short.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <gadget>
        <name>FloatToShortAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>FloatToUShortGadget</classname>

        <property><name>max_intensity</name><value>32767</value></property>
        <property><name>min_intensity</name><value>0</value></property>
        <property><name>intensity_offset</name><value>0</value></property>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
  
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
  
    <gadget>
        <name>RemoveROOversampling</name>
        <dll>gadgetron_mricore</dll>
	<classname>RemoveROOversamplingGadget</classname>
        <property>
            <name>constant_noise_variance</name>
            <value>false</value>
        </property>
    </gadget>

    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
	<classname>AcquisitionAccumulateTriggerGadget</classname>
        <property>
            <name>trigger_dimension</name>
            <value>repetition</value>
        </property>
        <property>
          <name>sorting_dimension</name>
          <value>slice</value>
        </property>
    </gadget>

    <gadget>
        <name>Buff</name>
        <dll>gadgetron_mricore</dll>
	<classname>BucketToBufferGadget</classname>
        <property>
            <name>N_dimension</name>
            <value></value>
        </property>
        <property>
          <name>S_dimension</name>
          <value></value>
        </property>
        <property>
          <name>split_slices</name>
          <value>true</value>
        </property>
    </gadget>

     <gadget>
      <name>FFT</name>
      <dll>gadgetron_mricore</dll>
      <classname>FFTGadget</classname>
     </gadget>

    <gadget>
      <name>Combine</name>
      <dll>gadgetron_mricore</dll>
      <classname>CombineGadget</classname>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>  

    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>

</gadgetronStreamConfiguration>
